# Created by: ache
# $FreeBSD$

PORTNAME=	patch
PORTVERSION=	2.7.5
CATEGORIES=	devel
MASTER_SITES=	GNU

MAINTAINER=	johans@FreeBSD.org
COMMENT=	GNU patch utility

LICENSE=	GPLv3

USES=		cpe charsetfix gmake tar:xz
GNU_CONFIGURE=	yes
#CONFIGURE_ARGS=	--program-prefix=g
CPE_VENDOR=	gnu

PLIST_FILES=	bin/patch man/man1/patch.1.gz

.include <bsd.port.mk>
