# $FreeBSD$

.include "Makefile.version"

BUILD_DEPENDS=		gmp>0:math/gmp
BUILD_DEPENDS+=		mpfr>0:math/mpfr
BUILD_DEPENDS+=		mpc>0:math/mpc
BUILD_DEPENDS+=		${LOCALBASE}/bin/flex:textproc/flex

GNU_CONFIGURE=		yes
USES=			gmake libtool perl5 tar:bzip2
USE_PERL5=		build
ALL_TARGET=		default
CFLAGS:=		${CFLAGS:N-march=*}
