# Created by: John Marino <marino@FreeBSD.org>
# $FreeBSD$

PORTNAME=	libdl
PORTVERSION=	1
CATEGORIES=	devel
MASTER_SITES=	# none
DISTFILES=	# none

MAINTAINER=	marino@FreeBSD.org
COMMENT=	Dummy static dl library

LICENSE=	BSD2CLAUSE

PLIST_FILES=	lib/libdl.a

do-extract:
	${MKDIR} ${WRKSRC}
	cp ${FILESDIR}/* ${WRKSRC}/

.include <bsd.port.mk>
