# Created by: Alexander Zhuravlev <zaa@zaa.pp.ru>
# $FreeBSD$

PORTNAME=	zlib
PORTVERSION=	1.2.11
CATEGORIES=	archivers
MASTER_SITES=	http://www.zlib.net/

MAINTAINER=	draco@marino.st
COMMENT=	ubiquitous compression library

HAS_CONFIGURE=	yes
CONFIGURE_ARGS=	--static

.include <bsd.port.mk>
